from __future__ import annotations

import app
from band_runtime_hardening import install_band_runtime_hardening
from band_ui import install_band_mode
from gaming_runtime_2026 import install_gaming_runtime_2026
from gaming_ui_2026 import install_gaming_ui_2026
from local_search_integration import install_local_search_integration
from modern_ui import install_modern_ui
from online_integration import install_online_integration
from online_search_bridge import install_online_search_bridge
from online_search_ui_2026 import install_online_search_ui_2026
from playback_adaptive import install_adaptive_arranger
from playback_adaptive_pressure import install_adaptive_pressure_model
from playback_adaptive_ui import install_adaptive_arranger_ui
from playback_advanced_ui import install_advanced_playback_profile
from playback_arranger_refinements import install_arranger_refinements
from playback_calibration_guidance import install_guided_calibration
from playback_calibration_provenance import install_calibration_provenance
from playback_calibration_ui import install_calibration_lab
from playback_evidence_refinements import install_evidence_refinements
from playback_overhaul import install_playback_overhaul
from ui_persistent_library import install_persistent_library
from ui_product_overhaul_v34 import install_product_ui_overhaul


# v3.4 keeps the verified v3.3 timing/safety layer, adds evidence-driven
# arrangement refinements, and ships the responsive product UI overhaul.
# The feature/band-mode-v35 branch layers the experimental Band Mode on top.
app.APP_VERSION = "3.4.0"

install_online_search_bridge()
install_modern_ui(app)
install_gaming_ui_2026(app)
install_online_integration(app)
install_online_search_ui_2026()
install_local_search_integration(app)
install_gaming_runtime_2026(app)
install_playback_overhaul(app)
install_advanced_playback_profile(app)
install_adaptive_arranger(app)
install_arranger_refinements(app)
install_adaptive_pressure_model(app)
install_adaptive_arranger_ui(app)
install_evidence_refinements(app)
install_calibration_lab(app)
install_guided_calibration(app)
install_calibration_provenance(app)
install_product_ui_overhaul(app)
install_persistent_library(app)
install_band_mode(app)
install_band_runtime_hardening(app)


if __name__ == "__main__":
    raise SystemExit(app.main())
